/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function *fib(stop = i => false) {
    yield 0;
    let last = 0;
    let next = 1;
    while(stop(last + next)) {
        [last, next] = [next, last + next];
        yield next;
    }
}

const isEven = i => i % 2 === 0;

const isLessThan = max => i => i < max;

const result = [...fib(isLessThan(4000000))].filter(isEven).reduce((acc, cur) => acc + cur);

console.log(result)